### ISSUE TITLE
Save SSH passphrase after first time unlocking private key

### ISSUE THREAD

**Issue by alanct-minted** [alanchrt/dotfiles#11]
Preferably without manually calling `ssh-add`

**Comment by alanct-minted** [comment]
http://unix.stackexchange.com/questions/168062/how-to-save-an-ssh-key-passphrase-in-gnome-keyring

**Comment by alanct-minted** [comment]
https://wiki.archlinux.org/index.php/GNOME/Keyring

**Comment by alanchrt** [comment]
All good on Fedora/GNOME
