### ISSUE TITLE
Make bootstrap script prompt for username and hostname

### ISSUE THREAD

**Issue by alanchrt** [alanchrt/dotfiles#122]
The username can be dynamically referenced in the bootstrap script, and both username and hostname can be substituted into a template for configuration.nix.

**Comment by alanctkc** [comment]
Do templates like this: https://stackoverflow.com/a/30872526/359287

Store configuration in a `host-configuration.nix` and `user-configuration.nix` and import into `configuration.nix`. Make sure `configuration.nix` is always only shared configuration that can be in source control (not template).

**Comment by alanchrt** [comment]
On fedora now
