### ISSUE TITLE
Bind brightness keys in i3

### ISSUE THREAD

**Issue by alanchrt** [alanchrt/dotfiles#79]
So I can wire them up to use i3blocks instead of notify-send.

Possibly wired up through here at present: `/etc/dbus-1/system.d/org.freedesktop.UPower.conf`

**Comment by alanctkc** [comment]
Nonono UPower can control keyboard backlight, but it's not doing screen brightness.

**Comment by alanctkc** [comment]
This may be more straightforward on NixOS?

**Comment by alanchrt** [comment]
Non-issue in GNOME
