### ISSUE TITLE
Consider using pass instead of LastPass

### ISSUE THREAD

**Issue by alanchrt** [alanchrt/dotfiles#87]
https://www.passwordstore.org/ and https://github.com/dannyvankooten/browserpass

Maybe https://github.com/zeapo/Android-Password-Store too

**Comment by alanct-minted** [comment]
And wire it up to dmenu: https://git.zx2c4.com/password-store/tree/contrib/dmenu

No brainer.

**Comment by alanct-minted** [comment]
Convert with script from LastPass CSV: https://git.zx2c4.com/password-store/tree/contrib/importers/lastpass2pass.rb

**Comment by alanct-minted** [comment]
Or gopass.

Also consider tomb to obscure services: https://github.com/roddhjav/pass-tomb

**Comment by alanct-minted** [comment]
https://github.com/carnager/rofi-pass/

(Use rofi, not dmenu)

**Comment by alanctkc** [comment]
In the transition consider binding lastpass in rofi: https://github.com/lastpass/lastpass-cli
